import { RegionCard } from '@/types/cards/region';

export const REGION_CARDS: RegionCard[] = [
  {
    id: "everglades-marsh",
    name: "Everglades Marsh",
    type: "region",
    biomeTags: ["🐊"],
    icons: [{ symbol: "🐊", meaning: "Swamp Biome" }],
    keywords: ["Swamp", "Marsh", "Dangerous"],
    onEnter: "Draw 1 Hazard (creature or environmental)",
    action: "Spend 1 Luck → Draw 1 Gear",
    rest: "Reduce 1 Weirdness",
    bonusZone: "Clue Token (counts as 1 Clue toward Mission objectives)",
    rules: ["The longer you stay, the less solid the ground feels"],
    flavor: "The longer you stay, the less solid the ground feels.",
    imagePrompt: "Vast sawgrass flats reflected in still water, cypress knees poking up, mist curling in neon-green dawn light"
  },
  {
    id: "cypress-bayou",
    name: "Cypress Bayou",
    type: "region",
    biomeTags: ["🐊", "🌳"],
    icons: [
      { symbol: "🐊", meaning: "Swamp Biome" },
      { symbol: "🌳", meaning: "Forest Biome" }
    ],
    keywords: ["Swamp", "Forest", "Mystic"],
    onEnter: "Moxie DC 9 → Success: avoid next Hazard; Failure: gain 1 Heat",
    action: "Sacrifice 1 Gear → auto-succeed next Grit check",
    rest: "Heal 1 Health (you find fresh water)",
    bonusZone: "Bayou Shrine: Spend 1 Luck to gain 1 Weirdness reduction",
    rules: ["Whispers drift through hanging vines… and sometimes replies"],
    flavor: "Whispers drift through hanging vines… and sometimes replies.",
    imagePrompt: "Ancient cypress trees draped with Spanish moss, waterlogged path winding through murky green shadows"
  },
  {
    id: "ghost-mall",
    name: "Ghost Mall",
    type: "region",
    biomeTags: ["🏙️"],
    icons: [{ symbol: "🏙️", meaning: "Urban Biome" }],
    keywords: ["Urban", "Abandoned", "Shelter"],
    onEnter: "Roll Weird check DC 9",
    rest: "Reduce 1 Weirdness",
    bonusZone: "Loot stores: Draw 1 Treasure",
    rules: ["Safe haven: No Hazard draws while resting"],
    flavor: "Once packed with shoppers, now only echoes remain.",
    imagePrompt: "Abandoned mall interior with broken skylights and overgrown plants"
  },
  {
    id: "galaxy-bar",
    name: "Galaxy Bar",
    type: "region",
    biomeTags: ["🏙️"],
    icons: [{ symbol: "🏙️", meaning: "Urban Biome" }],
    keywords: ["Tourist Trap", "Nightlife", "Weird"],
    onEnter: "None",
    action: "PLAY ARCADE (1 Action): Reduce Heat by 1, then roll d6 on Galaxy Bar Mini-Table",
    rest: "LOUNGE & CHILL (no Action): If you take no other actions this round, heal 1 Weirdness",
    bonusZone: "TALK TO BARTENDER (1 Action): Spend 1 Gear → Draw 1 Chaos or Artifact",
    rules: [
      "FAST TRAVEL (once per visit): Move to any Region you've previously visited (free)",
      "Special zone that only appears via specific triggers"
    ],
    flavor: "Cool neon, cryptid cocktails, and one working joystick. That's heaven around here.",
    imagePrompt: "A retro-futuristic arcade bar bathed in neon pink and teal, palm fronds casting silhouettes on rain-slick pavement"
  },
  {
    id: "alligator-farm",
    name: "Alligator Farm",
    type: "region",
    biomeTags: ["🐊"],
    icons: [{ symbol: "🐊", meaning: "Swamp Biome" }],
    keywords: ["Swamp", "Tourist", "Dangerous"],
    onEnter: "Draw 1 NPC (Gator Wrangler or Surprise Hazard)",
    action: "Pay 1 Food → Draw 1 Treasure",
    rest: "Take no action → Heal 1 Health but gain 1 Heat (stifling humidity)",
    bonusZone: "Expert Keeper (once/game): auto-avoid one creature Hazard",
    rules: ["Tourists take selfies… and the gators take souvenirs"],
    flavor: "Tourists take selfies… and the gators take souvenirs.",
    imagePrompt: "Rusty cages and feeding platforms by a muddy pond, neon-pastel warning signs, lurking jaws"
  },
  {
    id: "quicksand-bog",
    name: "Quicksand Bog",
    type: "region",
    biomeTags: ["🐊"],
    icons: [{ symbol: "🐊", meaning: "Swamp Biome" }],
    keywords: ["Swamp", "Hazard", "Movement"],
    onEnter: "Moxie DC 11 → Failure: become Immobilized until you spend 1 Action to free yourself",
    action: "Use Machete → +2 Bonus to free yourself or clear a path",
    rest: "Cannot rest here (bog sucks you in)",
    bonusZone: "Rope Anchor: Spend 1 Action + 1 Gear to auto-free all players",
    rules: ["What looks like solid ground is secretly your worst enemy"],
    flavor: "What looks like solid ground is secretly your worst enemy.",
    imagePrompt: "Sinking boot in golden muck, ripples spreading across luminescent green water"
  },
  {
    id: "mangrove-tangle",
    name: "Mangrove Tangle",
    type: "region",
    biomeTags: ["🐊"],
    icons: [{ symbol: "🐊", meaning: "Swamp Biome" }],
    keywords: ["Swamp", "Natural", "Resource"],
    onEnter: "Grit DC 9 → Success: +1 Luck; Failure: Lose 1 Action",
    action: "Spend 1 Action + 1 Gear → Draw 1 Clue",
    rest: "Heal 1 Weirdness (soothing shade)",
    bonusZone: "Hidden Den: Discard 1 Gear → Gain 1 Treasure Card",
    rules: ["Roots twist like serpents—twist yourself free if you can"],
    flavor: "Roots twist like serpents—twist yourself free if you can.",
    imagePrompt: "Knotted roots above dark water, shafts of neon-pastel light filtering through dense canopy"
  },
  {
    id: "abandoned-airboat-dock",
    name: "Abandoned Airboat Dock",
    type: "region",
    biomeTags: ["🐊"],
    icons: [
      { symbol: "🐊", meaning: "Swamp Biome" },
      { symbol: "🚤", meaning: "Vehicle" }
    ],
    keywords: ["Swamp", "Vehicle", "Safe"],
    onEnter: "Draw 1 Gear (vehicle or tool)",
    action: "Repair Vehicle (Grit DC 9) → Restore 1 Use to any Vehicle Gear",
    rest: "Safe (no Hazards)",
    bonusZone: "Spare Parts Cache: Search → Draw 1 Tool",
    rules: ["Engine husks creak in the breeze—if only they still ran"],
    flavor: "Engine husks creak in the breeze—if only they still ran.",
    imagePrompt: "Rusted dock boards leading to a stripped-out airboat hull, broken canopies swaying in humidity"
  },
  {
    id: "mosquito-infestation",
    name: "Mosquito Infestation Site",
    type: "region",
    biomeTags: ["🐊"],
    icons: [
      { symbol: "🐊", meaning: "Swamp Biome" },
      { symbol: "🌱", meaning: "Environmental" }
    ],
    keywords: ["Swamp", "Hazard", "Insect"],
    onEnter: "Gain 1 Weirdness (itchy bites)",
    action: "Use Bug Spray → Auto-success all Insect Hazards this turn",
    rest: "Gain 1 Heat (no cover)",
    bonusZone: "Natural Repellent: Spend 1 Action → Reduce 2 Weirdness",
    rules: ["One buzz, one bite… a hundred reminders you're not alone"],
    flavor: "One buzz, one bite… a hundred reminders you're not alone.",
    imagePrompt: "Clouds of tiny mosquitoes swirling over stagnant water, neon glow highlighting each wingbeat"
  },
  {
    id: "old-sugar-mill",
    name: "Old Sugar Mill Ruins",
    type: "region",
    biomeTags: ["🐊"],
    icons: [
      { symbol: "🐊", meaning: "Swamp Biome" },
      { symbol: "🏭", meaning: "Industrial" }
    ],
    keywords: ["Swamp", "Industrial", "Ruins"],
    onEnter: "Moxie DC 9 → Success: Draw 1 Treasure; Failure: Take 1 Damage",
    action: "Investigate (Charm DC 9) → Gain 1 Clue or reduce 1 Heat",
    rest: "Safe (solid floor)",
    bonusZone: "Crystalline Cache: Spend 1 Action + 1 Luck → Draw 1 Artifact-Proxy",
    rules: ["Once sweet, now sour—ghosts of labor hang in the air"],
    flavor: "Once sweet, now sour—ghosts of labor hang in the air.",
    imagePrompt: "Crumbling brick mill towers over reedy swamp, sugar-coated walls now cracked and moss-streaked"
  },
  {
    id: "forgotten-beach",
    name: "Forgotten Beach",
    type: "region",
    biomeTags: ["🏖️"],
    icons: [{ symbol: "🏖️", meaning: "Coastal Biome" }],
    keywords: ["Coastal", "Weather", "Fishing"],
    onEnter: "Draw 1 Hazard (Rip Current or Weather)",
    action: "Fish (Fishing Pole → Luck DC 4) → On success heal 1 Health; on 1 gain 1 Weirdness",
    rest: "Heal 1 Health or reduce 1 Weirdness (sand provides comfort)",
    bonusZone: "Tidal Pool: Spend 1 Action → draw 1 Gear",
    rules: ["Waves whisper secrets—but don't trust what they say"],
    flavor: "Waves whisper secrets—but don't trust what they say.",
    imagePrompt: "Half-sunken driftwood, tide-pools glowing neon-aqua amid bleached sand"
  },
  {
    id: "crashing-cliffs",
    name: "Crashing Cliffs",
    type: "region",
    biomeTags: ["🏖️"],
    icons: [
      { symbol: "🏖️", meaning: "Coastal Biome" },
      { symbol: "🏜️", meaning: "Exposed" }
    ],
    keywords: ["Coastal", "Exposed", "Dangerous"],
    onEnter: "Grit DC 9 → Failure: Take 1 Damage (falling rock)",
    action: "Survey (Moxie DC 9) → Success: gain 1 Clue; Failure: lose 1 Action",
    rest: "Cannot rest (dangerous)",
    bonusZone: "Cliff Cache: Spend 1 Action + 1 Action → Draw 1 Gear",
    rules: ["Every gust carries the roar of the abyss"],
    flavor: "Every gust carries the roar of the abyss.",
    imagePrompt: "Jagged rock faces plunging into foaming surf, neon pastel spray in the wind"
  },
  {
    id: "red-tide-strand",
    name: "Red Tide Strand",
    type: "region",
    biomeTags: ["🏖️"],
    icons: [
      { symbol: "🏖️", meaning: "Coastal Biome" },
      { symbol: "☣️", meaning: "Toxic" }
    ],
    keywords: ["Coastal", "Toxic", "Hazard"],
    onEnter: "Gain 1 Heat and 1 Weirdness (poisonous algae)",
    action: "Use Gas Mask (Consumable) → Auto-success Heat & Weirdness effects this visit",
    rest: "Heal 1 Weirdness (cool breeze)",
    bonusZone: "Washed-Up Relic: Spend 1 Action → Draw 1 Treasure",
    rules: ["The sea bleeds crimson—and everything that breathes chokes"],
    flavor: "The sea bleeds crimson—and everything that breathes chokes.",
    imagePrompt: "Blood-red water lapping at rotting shells on neon-tinged sand"
  },
  {
    id: "shipwreck-cove",
    name: "Shipwreck Cove",
    type: "region",
    biomeTags: ["🏖️"],
    icons: [{ symbol: "🏖️", meaning: "Coastal Biome" }],
    keywords: ["Coastal", "Salvage", "Safe"],
    onEnter: "Draw 1 Gear (Weapon or Tool)",
    action: "Salvage (Grit DC 9) → Success: gain 1 Gear; Failure: take 1 Damage",
    rest: "Safe (inside hull)",
    bonusZone: "Captain's Locker – Spend 1 Action → Draw 1 Artifact-Proxy",
    rules: ["Metal carcasses jut from the surf—treasure or trap?"],
    flavor: "Metal carcasses jut from the surf—treasure or trap?",
    imagePrompt: "Rusted hull half-buried in sand, barnacle-clad decks glittering neon-pastel"
  },
  {
    id: "saltwater-fishing-pier",
    name: "Saltwater Fishing Pier",
    type: "region",
    biomeTags: ["🏖️"],
    icons: [
      { symbol: "🏖️", meaning: "Coastal Biome" },
      { symbol: "🐟", meaning: "Creature" }
    ],
    keywords: ["Coastal", "Fishing", "Resource"],
    onEnter: "Moxie DC 9 → Success: Draw 1 Gear; Failure: Lose 1 Luck",
    action: "Fish (Fishing Pole → Luck DC 4) → Heal 1 Health on success",
    rest: "Gain 1 Heat (no shade)",
    bonusZone: "Bait Shop – Spend 1 Action → Draw 1 Gear (Consumable)",
    rules: ["Shouts of seagulls outnumber the creaks of boards"],
    flavor: "Shouts of seagulls outnumber the creaks of boards.",
    imagePrompt: "Weathered planks lined with rod holders, neon pastel bait buckets and gull droppings"
  },
  {
    id: "hurricane-refuge-camp",
    name: "Hurricane Refuge Camp",
    type: "region",
    biomeTags: ["🏖️"],
    icons: [
      { symbol: "🏖️", meaning: "Coastal Biome" },
      { symbol: "🌪️", meaning: "Weather" }
    ],
    keywords: ["Coastal", "Weather", "Safe"],
    onEnter: "Grit DC 9 → Success: Reduce 1 Heat; Failure: Gain 1 Heat",
    action: "Fortify (1 Action + 1 Gear) → Gain +2 Fortify for next Storm Hazard",
    rest: "Heal 1 Health or Reduce 2 Weirdness",
    bonusZone: "Supply Tent – Discard 1 Gear → Draw 2 Consumables",
    rules: ["Sandbags, canned goods, and false hope"],
    flavor: "Sandbags, canned goods, and false hope.",
    imagePrompt: "White tents lined in rows, hurricane warnings fluttering neon-red in gale winds"
  },
  {
    id: "ghost-mall",
    name: "Ghost Mall",
    type: "region",
    biomeTags: ["🏙️"],
    icons: [{ symbol: "🏙️", meaning: "Urban Biome" }],
    keywords: ["Urban", "Abandoned", "Safe"],
    onEnter: "Draw 1 NPC (Confused Tourist or Street Preacher)",
    action: "Scavenge (Luck DC 9) → Success: Draw 1 Gear; Failure: Gain 1 Heat",
    rest: "Safe (climate-controlled)",
    bonusZone: "Abandoned ATM – Spend 1 Action → Draw 1 Treasure",
    rules: ["Once a beacon of commerce, now an echoing shell"],
    flavor: "Once a beacon of commerce, now an echoing shell.",
    imagePrompt: "Empty storefronts, flickering neon SALE signs, dust motes in harsh fluorescent beams"
  },
  {
    id: "abandoned-gas-station",
    name: "Abandoned Gas Station",
    type: "region",
    biomeTags: ["🏙️"],
    icons: [
      { symbol: "🏙️", meaning: "Urban Biome" },
      { symbol: "⛽", meaning: "Vehicle" }
    ],
    keywords: ["Urban", "Vehicle", "Resource"],
    onEnter: "Draw 1 NPC (Questionable Vendor) or Hazard (Vehicle)",
    action: "Fill Gas Can (1 Action) → Gain Full Gas Can",
    rest: "Heal 1 Weirdness (quiet corner)",
    bonusZone: "Tool Rack – Spend 1 Action → Draw 1 Tool Gear",
    rules: ["Flickering pump lights, the smell of stale fuel"],
    flavor: "Flickering pump lights, the smell of stale fuel.",
    imagePrompt: "Rusted pump islands, broken windows, neon-pastel graffiti on walls"
  },
  {
    id: "police-roadblock",
    name: "Police Roadblock",
    type: "region",
    biomeTags: ["🏙️"],
    icons: [
      { symbol: "🏙️", meaning: "Urban Biome" },
      { symbol: "🚔", meaning: "Social" }
    ],
    keywords: ["Urban", "Social", "Restricted"],
    onEnter: "Charm DC 11 → Success: pass freely; Failure: Lose 1 Action & Gain 1 Heat",
    action: "Bribe (discard 1 Gear + Charm DC 9) → Pass or draw 1 Chaos",
    rest: "Cannot rest (guarded)",
    bonusZone: "Warrant File – Spend 1 Action → Draw 1 Clue",
    rules: ["Lights flash, questions mount, patience frays"],
    flavor: "Lights flash, questions mount, patience frays.",
    imagePrompt: "Barricades, uniformed officers, neon-red and blue reflections on wet asphalt"
  },
  {
    id: "industrial-canal",
    name: "Industrial Canal",
    type: "region",
    biomeTags: ["🏙️"],
    icons: [
      { symbol: "🏙️", meaning: "Urban Biome" },
      { symbol: "💧", meaning: "River" }
    ],
    keywords: ["Urban", "Water", "Toxic"],
    onEnter: "Grit DC 9 → Success: Draw 1 Treasure; Failure: Take 1 Damage",
    action: "Navigate (Moxie DC 9) → Success: gain 1 Luck; Failure: Lose 1 Action",
    rest: "Gain 1 Weirdness (toxic fumes)",
    bonusZone: "Maintenance Hatch – Spend 1 Action → Draw 1 Tool Gear",
    rules: ["Concrete banks hold tainted currents—tread carefully"],
    flavor: "Concrete banks hold tainted currents—tread carefully.",
    imagePrompt: "Rusted metal walkways over churning green-black water, warning signs in neon-paste"
  },
  {
    id: "rooftop-helipad",
    name: "Rooftop Helipad",
    type: "region",
    biomeTags: ["🏙️"],
    icons: [{ symbol: "🏙️", meaning: "Urban Biome" }],
    keywords: ["Urban", "Travel", "Exposed"],
    onEnter: "Moxie DC 11 → Success: Move immediately to any Urban Region; Failure: Take 1 Damage (misstep)",
    action: "Signal (1 Action + Gear) → Draw 1 Chaos card; reveal location",
    rest: "Heal 1 Health (open air)",
    bonusZone: "Emergency Rations – Spend 1 Action → Draw 1 Consumable",
    rules: ["Wind howls above the city's roar"],
    flavor: "Wind howls above the city's roar.",
    imagePrompt: "Painted H on weathered concrete, bounding box lines glowing pastel under cloudy sky"
  },
  {
    id: "tourist-strip",
    name: "Tourist Strip",
    type: "region",
    biomeTags: ["🏙️"],
    icons: [
      { symbol: "🏙️", meaning: "Urban Biome" },
      { symbol: "🎪", meaning: "Tourist Trap" }
    ],
    keywords: ["Urban", "Social", "Resource"],
    onEnter: "Luck DC 9 → Success: Draw 1 Gear; Failure: Gain 1 Heat",
    action: "People-Watch (Charm DC 9) → Success: Gain 1 Clue; Failure: Lose 1 Action",
    rest: "Safe but Gain 1 Heat (crowd)",
    bonusZone: "Souvenir Stand – Spend 1 Action → Draw 1 Treasure",
    rules: ["Neon signs, souvenir shops—and something lurking behind"],
    flavor: "Neon signs, souvenir shops—and something lurking behind.",
    imagePrompt: "Endless rows of gift shops, neon flamingos, selfie-stick wielding crowds"
  },
  {
    id: "mile-long-bridge",
    name: "Mile-Long Bridge",
    type: "region",
    biomeTags: ["🛣️"],
    icons: [{ symbol: "🛣️", meaning: "Highway Biome" }],
    keywords: ["Highway", "Movement", "Exposed"],
    onEnter: "Moxie DC 9 → Failure: Take 1 Damage (swaying)",
    action: "Race (Moxie DC 9) → Success: Move again 1 tile; Failure: Lose 1 Action",
    rest: "Cannot rest (exposed)",
    bonusZone: "Scenic Overlook – Spend 1 Action → Draw 1 Clue",
    rules: ["One misstep and you're falling into the deep"],
    flavor: "One misstep and you're falling into the deep.",
    imagePrompt: "Endless steel spans over glittering water, guardrails glowing in neon twilight"
  },
  {
    id: "rusted-traffic-jam",
    name: "Rusted Traffic Jam",
    type: "region",
    biomeTags: ["🛣️"],
    icons: [
      { symbol: "🛣️", meaning: "Highway Biome" },
      { symbol: "🚗", meaning: "Vehicle" }
    ],
    keywords: ["Highway", "Vehicle", "Restricted"],
    onEnter: "Lose 1 Action (stuck)",
    action: "Bicycle/Bike Gear (discard 1 Gear) → Ignore this effect and move normally",
    rest: "Heal 1 Health (stretch your legs)",
    bonusZone: "Car Trunk Cache – Spend 1 Action → Draw 1 Gear",
    rules: ["Horns honk—but nobody budges"],
    flavor: "Horns honk—but nobody budges.",
    imagePrompt: "Dozens of cars bumper-to-bumper under a pastel sky, steam rising from hoods"
  },
  {
    id: "rest-stop-diner",
    name: "Rest-Stop Diner",
    type: "region",
    biomeTags: ["🛣️"],
    icons: [
      { symbol: "🛣️", meaning: "Highway Biome" },
      { symbol: "🍲", meaning: "Food" }
    ],
    keywords: ["Highway", "Food", "Safe"],
    onEnter: "Draw 1 NPC (Motel Manager or Roadside Vendor)",
    action: "Eat (discard 1 Consumable) → Heal 2 Damage or Reduce 2 Weirdness",
    rest: "Heal 1 Health and Reduce 1 Weirdness",
    bonusZone: "Free Coffee – Spend 1 Action → Gain 1 Heat reduction next End Phase",
    rules: ["Pie's fresh—but so is the dread in your stomach"],
    flavor: "Pie's fresh—but so is the dread in your stomach.",
    imagePrompt: "Neon-lit diner booths, checkered floors, steaming mugs on a sticky counter"
  },
  {
    id: "decommissioned-tollbooth",
    name: "Decommissioned Tollbooth",
    type: "region",
    biomeTags: ["🛣️"],
    icons: [{ symbol: "🛣️", meaning: "Highway Biome" }],
    keywords: ["Highway", "Abandoned", "Resource"],
    onEnter: "Loot (Luck DC 9) → Success: Draw 1 Gear; Failure: Gain 1 Heat",
    action: "Repair (Duct Tape or Repair Tool) → Success: Draw 1 Tool Gear",
    rest: "Safe (solid structure)",
    bonusZone: "Toll Collector's Log – Spend 1 Action → Draw 1 Clue",
    rules: ["No one's collecting tolls… but someone left something behind"],
    flavor: "No one's collecting tolls… but someone left something behind.",
    imagePrompt: "Rusty booth with faded TOLL sign, cracked glass, neon crackle in shadows"
  },
  {
    id: "overturned-tanker",
    name: "Overturned Tanker Site",
    type: "region",
    biomeTags: ["🛣️"],
    icons: [
      { symbol: "🛣️", meaning: "Highway Biome" },
      { symbol: "☣️", meaning: "Toxic" }
    ],
    keywords: ["Highway", "Toxic", "Hazard"],
    onEnter: "Gain 1 Heat & Take 1 Damage (chemical spill)",
    action: "Contain (Grit DC 11) → Success: Reduce 2 Heat; Failure: Gain 1 Weirdness",
    rest: "Cannot rest (poisonous fumes)",
    bonusZone: "Hazmat Cache – Spend 1 Action → Draw 1 Tool or Consumable",
    rules: ["Acidic rain and slick toxin pools—stay upwind"],
    flavor: "Acidic rain and slick toxin pools—stay upwind.",
    imagePrompt: "Crashed tanker leaking neon-green fluid across cracked asphalt"
  },
  {
    id: "pine-barrens",
    name: "Pine Barrens",
    type: "region",
    biomeTags: ["🌳"],
    icons: [{ symbol: "🌳", meaning: "Forest Biome" }],
    keywords: ["Forest", "Natural", "Resource"],
    onEnter: "Grit DC 9 → Success: +1 Luck; Failure: Take 1 Damage",
    action: "Forage (Luck DC 9) → Success: Draw 1 Consumable; Failure: Gain 1 Weirdness",
    rest: "Heal 1 Health",
    bonusZone: "Hunting Blind – Spend 1 Action → Draw 1 Gear or Treasure",
    rules: ["Tall pines hide more than just shade"],
    flavor: "Tall pines hide more than just shade.",
    imagePrompt: "Dense pine trunks rising skyward, needle-strewn floor glowing under neon shafts"
  },
  {
    id: "fire-tower-lookout",
    name: "Fire Tower Lookout",
    type: "region",
    biomeTags: ["🌳"],
    icons: [{ symbol: "🌳", meaning: "Forest Biome" }],
    keywords: ["Forest", "Observation", "Safe"],
    onEnter: "Moxie DC 9 → Success: view entire map layout; Failure: Gain 1 Weirdness (vertigo)",
    action: "Signal (1 Action + Gear) → Draw 1 Chaos card and reveal location",
    rest: "Safe (enclosed cabin)",
    bonusZone: "Tower Supply – Spend 1 Action → Draw 2 Gear cards",
    rules: ["The world stretches below, but so do the secrets"],
    flavor: "The world stretches below, but so do the secrets.",
    imagePrompt: "Wooden tower platform above treetops, panoramic vista under neon sky"
  },
  {
    id: "lumber-mill-clearing",
    name: "Lumber Mill Clearing",
    type: "region",
    biomeTags: ["🌳"],
    icons: [
      { symbol: "🌳", meaning: "Forest Biome" },
      { symbol: "🏭", meaning: "Industrial" }
    ],
    keywords: ["Forest", "Industrial", "Resource"],
    onEnter: "Draw 1 Hazard (Creature or Environmental)",
    action: "Scavenge (Grit DC 9) → Success: Draw 1 Gear; Failure: Lose 1 Action",
    rest: "Reduce 1 Weirdness (calming hum of saws)",
    bonusZone: "Timber Pile – Spend 1 Action → Draw 1 Tool Gear",
    rules: ["Axes and sawdust ghosts still linger here"],
    flavor: "Axes and sawdust ghosts still linger here.",
    imagePrompt: "Stacks of logs, rusting sawmill machinery, neon pastel sawdust mist"
  },
  {
    id: "hidden-bunker",
    name: "Hidden Bunker Entrance",
    type: "region",
    biomeTags: ["🌳"],
    icons: [
      { symbol: "🌳", meaning: "Forest Biome" },
      { symbol: "⛏️", meaning: "Underground" }
    ],
    keywords: ["Forest", "Underground", "Secret"],
    onEnter: "Search (Moxie DC 11) → Success: reveal hidden chamber (draw 1 Treasure); Failure: trigger minor Hazard",
    action: "Open Hatch (Grit DC 9) → Success: rest inside (heal 2 Health); Failure: Lose 1 Action",
    rest: "Safe inside bunker",
    bonusZone: "Ammo Crate – Spend 1 Action → Draw 1 Weapon Gear",
    rules: ["What was buried here—and what still listens?"],
    flavor: "What was buried here—and what still listens?",
    imagePrompt: "Camouflaged hatch in undergrowth, rusted handle, dim neon glow from below"
  },
  {
    id: "wolf-creek",
    name: "Wolf Creek Campground",
    type: "region",
    biomeTags: ["🌳"],
    icons: [{ symbol: "🌳", meaning: "Forest Biome" }],
    keywords: ["Forest", "Camping", "Safe"],
    onEnter: "Draw 1 NPC (Desperate Survivor) or Hazard (Panther Screech)",
    action: "Campfire (1 Action + Fuel) → Heal 1 Health and Reduce 1 Weirdness",
    rest: "Heal 1 Weirdness (warm fire)",
    bonusZone: "Lost Tent – Spend 1 Action → Draw 1 Clue",
    rules: ["Bonfires crackle, but eyes glare from the treeline"],
    flavor: "Bonfires crackle, but eyes glare from the treeline.",
    imagePrompt: "Flickering campfire ring, empty tents, shadows dancing among trees"
  },
  {
    id: "salt-flats",
    name: "Sweltering Salt Flats",
    type: "region",
    biomeTags: ["☀️"],
    icons: [{ symbol: "☀️", meaning: "Exposed Biome" }],
    keywords: ["Exposed", "Heat", "Hazard"],
    onEnter: "Gain 1 Heat",
    action: "Shade Search (Luck DC 9) → Success: Reduce 1 Heat; Failure: Gain 1 Weirdness",
    rest: "Gain 2 Weirdness (relentless sun)",
    bonusZone: "Mirrored Glass – Spend 1 Action → draw 1 Gear",
    rules: ["Sun beats down like a hammer on your skull"],
    flavor: "Sun beats down like a hammer on your skull.",
    imagePrompt: "Bleak white flats under blazing sun, heat haze warping distant horizon"
  },
  {
    id: "citrus-grove",
    name: "Sun-baked Citrus Grove",
    type: "region",
    biomeTags: ["☀️"],
    icons: [{ symbol: "☀️", meaning: "Exposed Biome" }],
    keywords: ["Exposed", "Food", "Resource"],
    onEnter: "Moxie DC 9 → Success: Draw 1 Consumable; Failure: Gain 1 Heat",
    action: "Pick Fruit (1 Action) → Draw 1 Consumable",
    rest: "Heal 1 Health",
    bonusZone: "Old Irrigation Well – Spend 1 Action → draw 1 Clue",
    rules: ["Oranges gleam—but juice stains more than thirst"],
    flavor: "Oranges gleam—but juice stains more than thirst.",
    imagePrompt: "Rows of orange trees under neon sunlight, fruit glowing vivid citrus"
  },
  {
    id: "bleached-parking",
    name: "Bleached Parking Lot",
    type: "region",
    biomeTags: ["☀️"],
    icons: [
      { symbol: "☀️", meaning: "Exposed Biome" },
      { symbol: "🏙️", meaning: "Urban Biome" }
    ],
    keywords: ["Exposed", "Urban", "Heat"],
    onEnter: "Lose 1 Luck (glare disorients)",
    action: "Scavenge (Luck DC 9) → Success: Draw 1 Gear; Failure: Gain 1 Heat",
    rest: "Safe but Gain 1 Heat (no shade)",
    bonusZone: "Abandoned Vending Machine – Spend 1 Action → Draw 1 Consumable",
    rules: ["White lines bake under endless sky"],
    flavor: "White lines bake under endless sky.",
    imagePrompt: "Faded asphalt grid, paint cracking, neon reflections in puddles"
  },
  {
    id: "flooded-farmland",
    name: "Flooded Farmland",
    type: "region",
    biomeTags: ["☀️"],
    icons: [
      { symbol: "☀️", meaning: "Exposed Biome" },
      { symbol: "💧", meaning: "River" }
    ],
    keywords: ["Exposed", "Water", "Hazard"],
    onEnter: "Grit DC 9 → Failure: Take 1 Damage (drowning hazard)",
    action: "Wade (Moxie DC 9) → Success: Draw 1 Gear; Failure: Lose 1 Action",
    rest: "Cannot rest (wet)",
    bonusZone: "Submerged Barn – Spend 1 Action → Draw 1 Clue",
    rules: ["Rows of crops drown beneath murky water"],
    flavor: "Rows of crops drown beneath murky water.",
    imagePrompt: "Sunken fence posts in standing water, soggy fields under pastel sky"
  },
  {
    id: "toxic-sewer",
    name: "Toxic Sewer Junction",
    type: "region",
    biomeTags: ["🕳️"],
    icons: [
      { symbol: "🕳️", meaning: "Underground Biome" },
      { symbol: "☣️", meaning: "Toxic" }
    ],
    keywords: ["Underground", "Toxic", "Hazard"],
    onEnter: "Gain 1 Weirdness & 1 Heat (fumes)",
    action: "Mask Up (Gas Mask) → Auto-success here; Else Grit DC 11 → Failure: Take 1 Damage",
    rest: "Gain 1 Weirdness (wild)",
    bonusZone: "Hidden Tunnel – Spend 1 Action → Move to any Sewer tile",
    rules: ["Stench so thick it sticks to your lungs"],
    flavor: "Stench so thick it sticks to your lungs.",
    imagePrompt: "Rusted pipes overhead dripping neon-green sludge onto cracked tiles"
  }
];
