// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yinqaphicibsdqitxunm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpbnFhcGhpY2lic2RxaXR4dW5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNzY4MTgsImV4cCI6MjA2MDY1MjgxOH0.6ZCCYmy3utMbex6jX0S4NunqOaXoW-3RvX5lYu27rMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);